[package]
name = "dobbydb-common-catalog"
version = {workspace = true}
edition = {workspace = true}

[dependencies]
toml = "0.9.2"
serde = { version = "1.0.219", features = ["derive"] }
dobbydb-common-base = {workspace = true}
datafusion = {workspace = true}
async-trait = {workspace = true}
